# Generated by Django 4.1.5 on 2023-04-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=50)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Not-started', 'Not-started'), ('In-progess', 'In-progress'), ('Completed', 'Completed')], max_length=50)),
            ],
        ),
    ]
